taskproject/regapp/urls.py
from django.urls import path

from . import views
app_name='regapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

taskproject/taskapp/urls.py
from django.urls import path

from . import views
app_name='taskapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('details/', views.details, name='details'),
    path('thanks/', views.thanks, name='thanks'),
    path('form/operations/', views.operations, name='operations'),
    path('form/', views.form, name='form'),
]

taskproject/taskproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskapp.urls')),
    path('', include('regapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

taskproject/regapp/models.py
from django.db import models

# Create your models here.

taskproject/taskapp/models.py
from django.db import models

# Create your models here.
class Place(models.Model):
    name=models.CharField(max_length=222)
    img=models.ImageField(upload_to='pics')
    desc=models.TextField()

    def __str__(self):
        return self.name

class People(models.Model):
    name=models.CharField(max_length=222)
    img=models.ImageField(upload_to='pics')
    desc=models.TextField()

    def __str__(self):
        return self.name

taskproject/regapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.

def register(request):
    regsuccess=False
    msg=''
    uname=''
    if request.method=='POST':
        uname = request.POST["username"]
        fname = request.POST["fname"]
        lname = request.POST["lname"]
        email = request.POST["email"]
        pwd1 = request.POST["password1"]
        pwd2 = request.POST["password2"]
        if User.objects.filter(username=uname).exists():
            msg=f'Username {uname} is already taken. use another Username'
            messages.info(request,msg)
            print(msg)
            return render(request, 'reg.html', {'msg': msg, 'regsuccess': regsuccess, 'uname': uname})
        elif User.objects.filter(email=email).exists():
            msg=f'Email {email} is already taken. use another email'
            messages.info(request,msg)
            print(msg)
            return render(request, 'reg.html', {'msg': msg, 'regsuccess': regsuccess, 'uname': uname})
        elif pwd1 != pwd2:
            msg = 'Passwords not matching'
            messages.info(request, msg)
            print(msg)
            return render(request, 'reg.html', {'msg': msg, 'regsuccess': regsuccess, 'uname': uname})
        else:
            user=User.objects.create_user(username=uname,first_name=fname,last_name=lname,email=email,password=pwd1)
            user.save()
            msg=f'User {uname} registered successfully'
            messages.info(request, msg)
            print(msg)
            regsuccess=True
            return render(request,'login.html',{'msg':msg,'regsuccess':regsuccess,'uname':uname})
    return render(request,'reg.html',{'msg':msg,'regsuccess':regsuccess,'uname':uname})

def login(request):
    loginsuccess,msg,uname=False,'',''
    if request.method=='POST':
        uname=request.POST['uname']
        pwd=request.POST['pwd']
        user=auth.authenticate(username=uname,password=pwd)
        if user is not None:
            auth.login(request,user)
            msg=f'User {uname} logged in successfully'
            loginsuccess=True
            messages.info(request, msg)
            print(msg)
            return render(request,'index.html',{'msg':msg,'loginsuccess':loginsuccess,'uname':uname})
        else:
            msg='invalid username or password'
            messages.info(request, msg)
            print(msg)
            return render(request,'login.html',{'msg':msg,'loginsuccess':loginsuccess,'uname':uname})
    return render(request, 'login.html', {'msg': msg, 'loginsuccess': loginsuccess, 'uname': uname})


def logout(request):
    logoutsuccess=True
    auth.logout(request)
    msg='logged out successfully'
    print(msg)
    return render(request, 'index.html', {'msg': msg, 'logoutsuccess': logoutsuccess})

taskproject/taskapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Place,People
# Create your views here.

def index(request):
    allpix=Place.objects.all()
    allppl=People.objects.all()
    return render(request,'index.html',{'allpix':allpix,'allppl':allppl,'loginsuccess':False})


def about(request):
    sss=['Bharat Mata ki jai',  'Using Jinja']
    return render(request,'about.html',{'abc':sss})
def contact(request):
    return HttpResponse('contact is here')
def details(request):
    return render(request,'details.html')
def thanks(request):
    return HttpResponse('thanks is here')
def form(request):
    return render(request,'form.html')
def operations(request):
    a = int(request.GET['a'])
    b = int(request.GET['b'])
    return render(request,'result.html',\
                  {'add':a+b,'sub':a-b,'mul':a*b,'div':a/b,'a':a,'b':b})

taskproject/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body style="background-color:maroon;">
<h3 style="color:skyblue;">
This is templates/about.html.
<br><br>
passing jinja variable.
<br><br>
this is passed from views.py =
    <br><br>
    {{abc}}
</h3>
</body>
</html>

taskproject/templates/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Travel App</title>
        <!-- CSS FILES -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&display=swap" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">
        <link href="{% static 'css/templatemo-tiya-golf-club.css' %}" rel="stylesheet">
    </head>

    <body>
{% include 'navbar.html' %}


{% block body %}
{% endblock %}
    </body>
        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-12 me-auto mb-5 mb-lg-0">
                        <a class="navbar-brand d-flex align-items-center" href="index.html">
                            <img src="{% static 'images/logo.png' %}" class="navbar-brand-image img-fluid" alt="">
                        </a>
                    </div>
                    <div class="col-lg-3 col-12">
                        <br>
                        <p class="copyright-text">Copyright © 2024 Travel App </p>
                    </div>
                </div>
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#81B29A" fill-opacity="1" d="M0,224L34.3,192C68.6,160,137,96,206,90.7C274.3,85,343,139,411,144C480,149,549,107,617,122.7C685.7,139,754,213,823,240C891.4,267,960,245,1029,224C1097.1,203,1166,181,1234,160C1302.9,139,1371,117,1406,106.7L1440,96L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path></svg>
        </footer>


        <!-- JAVASCRIPT FILES -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/jquery.sticky.js' %}"></script>
        <script src="{% static 'js/click-scroll.js' %}"></script>
        <script src="{% static 'js/animated-headline.js' %}"></script>
        <script src="{% static 'js/modernizr.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>

</html>

taskproject/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
This is templates/details.html

</body>
</html>

taskproject/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>input</title>
</head>
<body>

<form action="operations/" method="get">
    <input type="text" name="a" placeholder="number 1">
    <input type="text" name="b" placeholder="number 2">
    <input type="submit">
</form>

</body>
</html>

taskproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
        <main>

            <section class="hero-section d-flex justify-content-center align-items-center" id="section_1">

                <div class="section-overlay"></div>

                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#3D405B" fill-opacity="1" d="M0,224L34.3,192C68.6,160,137,96,206,90.7C274.3,85,343,139,411,144C480,149,549,107,617,122.7C685.7,139,754,213,823,240C891.4,267,960,245,1029,224C1097.1,203,1166,181,1234,160C1302.9,139,1371,117,1406,106.7L1440,96L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path></svg>

                <div class="container">
                    <div class="row">

                        <div class="col-lg-6 col-12 mb-5 mb-lg-0">
                            <h2 class="text-white">Welcome to the club</h2>

                            <h1 class="cd-headline rotate-1 text-white mb-4 pb-2">
                                <span>This Travel App is</span>
                                <span class="cd-words-wrapper">
                                    <b class="is-visible">Modern</b>
                                    <b>Creative</b>
                                    <b>Lifestyle</b>
                                </span>
                            </h1>
                        </div>
                    </div>
                </div>

                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#ffffff" fill-opacity="1" d="M0,224L34.3,192C68.6,160,137,96,206,90.7C274.3,85,343,139,411,144C480,149,549,107,617,122.7C685.7,139,754,213,823,240C891.4,267,960,245,1029,224C1097.1,203,1166,181,1234,160C1302.9,139,1371,117,1406,106.7L1440,96L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path></svg>
            </section>


            <section class="about-section section-padding" id="section_2">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-12 col-12 text-center">
                            <h2 class="mb-lg-5 mb-4">About Travel App</h2>
                        </div>

                        <div class="col-lg-12 col-12 text-center me-auto mb-4 mb-lg-0">

                            <p><strong>"A Seamless Journey with Our Travel Web App"</strong><br>


In the fast-paced world we live in, planning the perfect vacation can be a daunting task. The plethora of destinations, accommodations, and activities available can overwhelm even the most seasoned travelers. This is where our travel web app, "Wanderlust Companion," comes to the rescue, offering a seamless and efficient solution for planning, booking, and experiencing unforgettable travel vacations.

Wanderlust Companion is designed with the modern traveler in mind, providing a user-friendly interface that simplifies the entire travel planning process. Whether you're an adventure seeker, a culture enthusiast, or someone simply looking to unwind, our app caters to all preferences and ensures a personalized and memorable journey.
</p>

                        </div><div class="br"><br></div>
{% for i in allpix %}
                        <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0 mb-md-0"><br>
                            <div class="member-block">
                                <div class="member-block-image-wrap">
                                    <img src="{{i.img.url}}" class="member-block-image img-fluid" alt="">
                                </div>

                                <div class="member-block-info d-flex align-items-center">
                                    <h4>{{i.name}}</h4>

                                    <p class="ms-auto">{{i.desc}}</p>
                                </div>
                            </div>
                        </div>
{% endfor %}


                    </div>
                </div>
            </section>



                         <section class="about-section section-padding" >
                <div class="container">
                    <div class="row">           {% for i in allppl %}


                        <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0 mb-md-0">
                            <div class="member-block">
                                <div class="member-block-image-wrap">
                                    <img src="{{i.img.url}}" class="member-block-image img-fluid" alt="" width="100px" height="300px" >
                                </div>

                                <div class="member-block-info d-flex align-items-center">
                                    <h4>{{i.name}}</h4>

                                    <p>{{i.desc}}</p>
                                </div>
                            </div>
                        </div>

{% endfor %}          </div>
                        </div>
            </section>
        </main>


                {% endblock %}

taskproject/templates/indexlogin.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>STATIC page tutorial</title>
    </head>
<body style="background-image:url('{% static "images/beach.jpg" %}');background-repeat:no-repeat;">

    {% if user.is_authenticated %}
        <h4>hello {{user.username}}. u have successfully logged in</h4>
        <label style="background-color:white;"><a href="/logout"> logout </a></label>
    {% else %}
        <label style="background-color:white;"><a href="/register"> register </a></label>
        <label style="background-color:white;"><a href="/login"> login </a></label>
    {% endif %}
</body>
</html>

taskproject/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<section class="contact-section section-padding" id="section_5"><div class="container"><div class="row"><div class="col-lg-5 col-12">
<form action="{% url 'regapp:login' %}" method="post" class="custom-form contact-form">{% csrf_token %}<h2 class="mb-4 pb-2">Login: {{msg}}</h2>
<div class="row">
<div class="col-lg-6 col-md-6 col-12"><div class="form-floating"><input type="text" name="uname" id="Username" class="form-control" placeholder="Username"><label >Username</label></div></div>
<div class="col-lg-6 col-md-6 col-12"><div class="form-floating"><input type="password" name="pwd" id="Password" class="form-control" placeholder="Password"><label >Password</label></div></div>
<div class="col-lg-12 col-12"><button type="submit" class="form-control">Login</button></div></div>
</form>
</div><div class="col-lg-6 col-12"><div class="contact-info mt-5"><img src="{% static 'images/WorldMap.svg' %}" class="img-fluid" ></div></div></div></div></section>

{% endblock %}

taskproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color:black;"><div class="container">
                        <img src="{% static 'images/logo.png' %}" class="navbar-brand-image img-fluid">
                        <div class="d-none d-lg-block ms-lg-3">
                            <a class="btn  custom-border-btn">Travel App</a>
                        </div>
<div class="row" style="position:relative;float: right;"><div class="col d-none d-lg-block ms-lg-3">
<a class="btn custom-btn custom-border-btn" href="{% url 'taskapp:index' %}" role="button">Home</a></div>

    {% if loginsuccess %}
<div class="col d-none d-lg-block ms-lg-3"><a class="btn custom-btn custom-border-btn" role="button">{{uname}} logged in</a></div>
<div class="col d-none d-lg-block ms-lg-3"><a class="btn custom-btn custom-border-btn" href="{% url 'regapp:logout' %}" role="button">Logout</a></div>
{% else %}
<div class="col d-none d-lg-block ms-lg-3"><a class="btn custom-btn custom-border-btn" href="{% url 'regapp:login' %}" role="button">Login</a></div>
    {% endif %}
    {% if regsuccess %}
<div class="col d-none d-lg-block ms-lg-3"><a class="btn custom-btn custom-border-btn" role="button">{{uname}} registered successfully</a></div>
{% else %}
<div class="col d-none d-lg-block ms-lg-3"><a class="btn custom-btn custom-border-btn" href="{% url 'regapp:register' %}" role="button" >Register</a></div>
    {% endif %}
</div></div></nav>

taskproject/templates/reg.html
{% extends 'base.html' %}{% load static %}

{% block body %}

{% for msg in messages %}
{{msg}}
{% endfor %}
<section class="membership-section section-padding"><div class="container"><div class="row"><div class="col-lg-5 col-12 mx-auto">
<form action="{% url 'regapp:register' %}" method="post" class="custom-form membership-form shadow-lg" role="form">{% csrf_token %}
<h4 class="text-white mb-4">Register: {{msg}}</h4>

<div class="form-floating"><input type="text" name="username" class="form-control" placeholder="Username"><label>Username</label></div>
<div class="form-floating"><input type="text" name="fname" class="form-control" placeholder="First Name"><label>First Name</label></div>
<div class="form-floating"><input type="text" name="lname" class="form-control" placeholder="Last Name"><label>Last Name</label></div>
<div class="form-floating"><input type="email" name="email" class="form-control" placeholder="Email"><label>Email</label></div>
<div class="form-floating"><input type="password" name="password1" class="form-control" placeholder="Password"><label>Password</label></div>
<div class="form-floating"><input type="password" name="password2" class="form-control" placeholder="Confirm Password"><label>Confirm Password</label></div>
<button type="submit" class="form-control">Register</button>
</div></form></div></div></div></section>
{% endblock %}

taskproject/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>
<p>
Result of adding: {{a}} + {{b}} is {{add}} <br>
Result of subtracting: {{a}} - {{b}} is {{sub}}<br>
Result of multiplying: {{a}} * {{b}} is {{mul}}<br>
Result of dividing: {{a}} / {{b}} is {{div}}<br>
</p>
</body>
</html>